# Generated by Django 3.0.3 on 2020-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200513_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
