# Generated by Django 3.0.3 on 2020-05-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200513_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
