# Generated by Django 3.0.3 on 2020-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200517_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='bio',
            field=models.CharField(max_length=300),
        ),
    ]
