# Generated by Django 3.0.3 on 2020-05-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
