# Generated by Django 3.0.3 on 2020-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200508_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
