# Generated by Django 3.0.3 on 2020-05-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200508_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='event_image_one')),
                ('image2', models.ImageField(blank=True, upload_to='event_image_two')),
                ('image3', models.ImageField(blank=True, upload_to='event_image_three')),
                ('image4', models.ImageField(blank=True, upload_to='event_image_four')),
                ('image5', models.ImageField(blank=True, upload_to='event_image_five')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
